### ISSUE TITLE
Add offline support

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#10]

**Comment by roel-v** [comment]
I just got an Electron version running which would allow a standalone/offline installer to be build:

![image](https://github.com/Pattern-Projector/pattern-projector/assets/568567/e380720b-e971-4ebb-9e3b-b5c2cf00855b)

This is using the newlook branch. It's using a development version of Electron, i.e. running from a dev server on localhost and not with a completely separate built .exe yet. From what I understand this shouldn't be too hard to add, it's only a matter of configuring things correctly, but until about 3 hours ago I didn't even know how to run a React app on my local machine so I'm just figuring things out as I go.

How do you envisage this? You want me to put all this together? For Windows would you prefer an MSI or NSIS installer? Do you care about Linux support at all? I don't know anything about Macs but there will probably be sewists with a Mac - Linux users will be rare in that population I'd think. I don't know yet if there is some way of cross compiling for Mac from Windows either. Ideas and/or direction welcome.

**Comment by courtneypattison** [comment]
> I just got an Electron version running which would allow a standalone/offline installer to be build:
> 
> ![image](https://private-user-images.githubusercontent.com/568567/307283030-e380720b-e971-4ebb-9e3b-b5c2cf00855b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODk0MTUsIm5iZiI6MTcwODY4OTExNSwicGF0aCI6Ii81Njg1NjcvMzA3MjgzMDMwLWUzODA3MjBiLWU5NzEtNGViYi05ZTNiLWI1YzJjZjAwODU1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMTUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjE1Nzg0OGM4MDVkMGMwZTMyMjU4MTQxZTYxZmM0MmNjZWE0NWJjNjUzODg1M2MyYmI5YTMwMDQ0YWE2NWRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ldbUGEQELzKw8nu39nuliahAYebNowQbnxzCNmDq9g4)
> 

This looks great!

> This is using the newlook branch. It's using a development version of Electron, i.e. running from a dev server on localhost and not with a completely separate built .exe yet. From what I understand this shouldn't be too hard to add, it's only a matter of configuring things correctly, but until about 3 hours ago I didn't even know how to run a React app on my local machine so I'm just figuring things out as I go.
> 

I'm also just figuring things out as I go!

> How do you envisage this? You want me to put all this together? For Windows would you prefer an MSI or NSIS installer? Do you care about Linux support at all? I don't know anything about Macs but there will probably be sewists with a Mac - Linux users will be rare in that population I'd think. I don't know yet if there is some way of cross compiling for Mac from Windows either. Ideas and/or direction welcome.

The app is a PWA, which I only learned about a week or two ago when my husband watched a YouTube about them, so I know very little about how they work. I added the bare minimum to make it a PWA, so people could download it as a desktop or phone app. The way to make the PWA have offline support is by adding a [service worker](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Offline_Service_workers). I would prefer this method because I don't want to have to deal with permissions issues. It seems like PDFStitcher has non stop complaints about not being able to open it because of missing security exclusions.

I do have some data on what operating systems people are using from the site analytics (filtered by visits to the /calibrate route). 
<img width="611" alt="Screenshot 2024-02-23 at 7 11 18 AM" src="https://github.com/Pattern-Projector/pattern-projector/assets/5465100/314cba13-5d58-4c8a-96d6-c30abdf190dc">

What do you think?

**Comment by courtneypattison** [comment]
That's a great idea. The install icon on Chrome is so subtle.

**Comment by roel-v** [comment]
Re: that Electron version, fair enough on wanting to keep it as a PWA, although I do think the PWA concept is quite foreign to a lot of people; and that's not even counting for Apple effectively killing off PWA's on iOS in their struggle with the European Commission. Let's see.

In the mean time, I have a branch in my fork at https://github.com/roel-v/pattern-projector/tree/electron to keep a log of how to get it working, in case it's ever useful in the future.

**Comment by hluedeke** [comment]
> In the mean time, I have a branch in my fork at https://github.com/roel-v/pattern-projector/tree/electron to keep a log of how to get it working, in case it's ever useful in the future.

I think it is very useful!

I'm guessing Courtney is more a web dev and less a desktop dev (as am I), and I am definitely not comfortable with desktop builds. If you want to build it out and maintain it, I think it's a great addition. I just think neither of us wants to maintain it longterm 😜 (eg. new operating systems, computer chip manufacturers - thanks Apple!, etc)

**Comment by courtneypattison** [comment]
Thank you for sharing @roel-v! It could be something to consider with the future of PWAs being uncertain. I am more comfortable with web development. I released a tiny Android app a few years ago and it's been so much upkeep with all the new requirements put out by Google. Websites are so much less maintenance!
