### ISSUE TITLE
Add grid snapping

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#100]
As mentioned mentioned in issue #96 , some people move patterns to make length adjustments. Would it be a good idea to add togglable grid snapping when dragging a pattern? You could set it to snap to 1/8, 1/4, 3/8, 1/2, 1 inch, etc movements. Would allow for more precision in adjustment.

**Comment by courtneypattison** [comment]
I like this idea. It might be nice to have something like press an arrow key and have it move by 2.5 inches or whatever your adjustment is using a value from a text box or something like that.

**Comment by j-huff** [comment]
added grid snapping to drag movement delta in #154
