### ISSUE TITLE
Hide menu buttons after timeout and show on hover/tap

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#107]
Someone has requested this because the layers and show buttons keep getting in the way. I had this in PP at some point and honestly can't remember why we took it out lol. Maybe because it could be confusing on tablet with having to tap?

**Comment by hluedeke** [comment]
This isn’t exactly the reason we took it out, but the previous version had an invisible div that didn’t allow people to use mouse events on the side of the screen.

Do we hide/show all menus with this feature? Or just the buttons? With the continuing addition of new things, it feels like we need some menu state management (or at least we will). Maybe we show the “last state” all the menus were in? Also, should this be the default behavior, or should it be triggered by something (eg. a key)?

I would like to take a look at menu management some point, but I just haven’t had time yet!

**Comment by courtneypattison** [comment]
> This isn’t exactly the reason we took it out, but the previous version had an invisible div that didn’t allow people to use mouse events on the side of the screen.

Ah, thats why!

> 
> Do we hide/show all menus with this feature? Or just the buttons?

I think I'd probably prefer just the buttons. When we had it before, I kind of felt annoyed by my menu disappearing all the time. What do you think?

>With the continuing addition of new things, it feels like we need some menu state management (or at least we will). Maybe we show the “last state” all the menus were in?

I think people would appreciate that. It's nice to go back to how things were when you left them.

>Also, should this be the default behavior, or should it be triggered by something (eg. a key)?

If it's key based we have to think of tablet users and I'm not sure how to resolve that one.

> 
> I would like to take a look at menu management some point, but I just haven’t had time yet!

I feel you! I'm going to try to work less on PP this week and slow down the release process so I'm not constantly introducing issues!

**Comment by courtneypattison** [comment]
Maybe roll #78 into this one as well?

**Comment by courtneypattison** [comment]
Completed in #291 :)
