### ISSUE TITLE
Small visual bug when switching units

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#110]
When switching between cm and in, there's a single frame in which the canvas is redrawn incorrectly. This is low priority as I don't image people would be switching units like this, but it's a little jarring and should be fixed regardless.

**Comment by j-huff** [comment]
Seems to be happening because the canvas dedraws a frame in which ptDensity has been updated, but the localPerspective hasn't been yet. Fix will involve making sure localPerspective and ptDensity always agree with eachother in the draw function.

**Comment by hluedeke** [comment]
Are both ptDensity and localPerspective listed as dependencies on the draw function? It's possible that that function has too many dependencies causing unnecessary re-renders. I've seen that in at least one other place and corrected it. We may just need to trim the dependency list (on useEffect/useCallback/useMemo, whichever applies).

**Comment by courtneypattison** [comment]
You are so fast! I'll check out the fix now :) Thank you!
