### ISSUE TITLE
Mouse movement during page refresh causes calibration points to reset

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#114]
There's a bug where if you refresh the page while you are moving the mouse, the calibration points can reset to their default position. This is likely due to the decoupling of the points in the CalibrationCanvas, and some weirdness that happens during page load. Possible fix would be to prevent localPoints from updating points until the points have been loaded from localStorage? I'll look into it.

**Comment by courtneypattison** [comment]
I noticed this before picking up my son from school so I looked into it a little bit. I think maybe checking if pointToModify is null and returning early in the touch and mouse up handlers might fix it. I didn’t get a chance to test though and won’t be able to go on my computer until later when the kiddos are asleep.
