### ISSUE TITLE
Warning: optional content group not found: 10r

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#12]
Not displaying pdf with this error message. Maybe missing layers? Maybe extra margin? Maybe corrupted? Should at least display error message. Workaround is to open in Inkscape and export fit to page.

**Comment by hluedeke** [comment]
This appears to be a missing layer, if I'm understanding my reading correctly. "Optional content" appears to be referencing layers.

**Comment by courtneypattison** [comment]
I believe so as well. However, she said the pdf wouldn't render in it's original state with all the layers, but I didn't get to try that out to see the error message. She just sent me a version that went through pdfstitcher, so it could be that this error message has nothing to do with the reason why it wasn't rendering. It might just be an artifact from running it through pdfstitcher.

It's hard to troubleshoot pdf issues when patterns usually aren't allowed to be shared. It would be nice to be able to get people to use something like [pdf-mangler](https://pypi.org/project/pdf-mangler/) (made by the creator of pdfstitcher) to make people more comfortable sending pdfs. Asking someone to use a python package seems unrealistic though.

**Comment by courtneypattison** [comment]
Someone else is having a similar problem with a pattern with large margins: the [winnie pants](https://www.madeformermaids.com/product/winniebundle/)

**Comment by hluedeke** [comment]
> She just sent me a version that went through pdfstitcher, so it could be that this error message has nothing to do with the reason why it wasn't rendering. It might just be an artifact from running it through pdfstitcher.

This is possible, and based on the fact that is warning and not an error, I'm actually thinking that this isn't the error that caused it to fail. There are many handler hooks on loading, so it's possible that since we haven't implemented all the possible error handlers that we aren't seeing the true cause yet.

Is it putting an error message on the screen? Or is just blank? I'd be happy to try it also, if you think a second pair of eyes would help.

**Comment by courtneypattison** [comment]
I don't have a copy of the file from the person yesterday because they wanted me to delete it, but the person who reported the issue today mentioned that it was a [Made for Mermaids pattern](https://www.madeformermaids.com/). I checked out their site and they have a lot of free patterns so I downloaded one to test it out. I ran it with PP with all the error checks I could find:
```
  <Document
      file={file}
      onLoadSuccess={onDocumentLoadSuccess}
      onLoadError={(e) => console.log(e.message)}
      onSourceError={(e) => console.log(e.message)}
    >
      <Page
        pageNumber={pageNumber}
        onGetAnnotationsError={(e) => console.log(e.message)}
        onGetStructTreeError={(e) => console.log(e.message)}
        onGetTextError={(e) => console.log(e.message)}
        onLoadError={(e) => console.log(e.message)}
        onRenderAnnotationLayerError={(e: any) => console.log(e.message)}
        onRenderError={(e) => console.log(e.message)}
        onRenderTextLayerError={(e) => console.log(e.message)}
      />
    </Document>
```
and none of them were triggered.

So I cloned the pdf.js library and setup their [webpack example](https://github.com/mozilla/pdf.js/tree/master/examples/webpack) to see if I could get it to render there and it did. I'm thinking maybe it's time to abandon react-pdf. I've already had to patch it once and as you mentioned in another issue, there's no way to access what we need for layers. What do you think?

**Comment by hluedeke** [comment]
> I've already had to patch it once and as you mentioned in another issue, there's no way to access what we need for layers. What do you think?

I'm all for using base libraries over wrappers when possible. Wrappers are nice for quick and dirty, but the underlying libraries usually win out in the long run! So, in short, I agree 100%.

**Comment by hluedeke** [comment]
> So I cloned the pdf.js library and setup their [webpack example](https://github.com/mozilla/pdf.js/tree/master/examples/webpack) to see if I could get it to render there and it did.

So, if I'm understanding you correctly, it would not load with react-pdf, but it did load with pdfjs? Interesting

**Comment by hluedeke** [comment]
Here's another thing I noticed. The PDFs that are failing for me are showing a little sad face. I don't know if this is what other users are seeing - it's very small, and I couldn't tell what it was until I changed my calibration grid. It looks like it might be a canvas error, like maybe running out memory or something like that:

https://stackoverflow.com/questions/57839322/sad-face-on-canvas-in-chrome

**Comment by courtneypattison** [comment]
I'm so sorry. I keep missing messages. I'm just seeing all these comments now! It seems like I'm not getting emails from this thread. I was wondering why you never responded and it turns out I was the goofus not responding!

Ok let's try to rip out react-pdf in favour of pdfjs. It was good at getting the MVP out there but it's just causing problems at this point. That being said, my attempt to add pdfjs-dist to the project was disastrous. I tried to follow the [webpack example](https://github.com/mozilla/pdf.js/tree/master/examples/webpack) to get access to the worker but even when I got the worker in `.next/static/chunks` I wasn't able to import it. Are you able to look into adding it to the project? I'll definitely try again but I'm not confident I'll be able to get it working quickly.

**Comment by hluedeke** [comment]
No problem - there's a lot of conversations going on right now. I can take a look at it if you want, just know it will probably take me awhile as well, haha.

**Comment by courtneypattison** [comment]
I got the layers working in the layers branch and tested out a made for mermaids file to see if the custom renderer would fix the issue with the large files opening. The good news is that it will open. The bad news is that the performance is horrible. I think pdfjs still makes more sense. Just thought I’d share. I don’t know much about pin pointing performance issues but I might try to look into it a bit to try to find the issue.

**Comment by courtneypattison** [comment]
I've been looking into the performance issue/not running with large files and have found that Firefox works for using them in Pattern Projector. A workaround for now!

**Comment by hluedeke** [comment]
> I've been looking into the performance issue/not running with large files and have found that Firefox works for using them in Pattern Projector. A workaround for now!

This might confirm my suspicion from earlier that browser-dependent maximum canvas size comes into play (could also be maximum file size). Glad to hear it's at least working somewhere.

**Comment by courtneypattison** [comment]
I was thinking that too, but even if you look at the canvas size maximums in that link you sent, Chrome has way higher maximums than Firefox. I'll keep investigating. Apparently nothing larger than a letter paper pattern will open on IOS, so this seems to be the main thing stopping tablet support right now. My brother-in-law is bringing his extra iPad for me to borrow this weekend so I'll finally have a device to test these issues on!

**Comment by hluedeke** [comment]
Oh wow. Thats really interesting 🤔 File handler upload size max maybe? But then you said that pdfjs would open it when react-pdf would not, so maybe not. This one’s tough, for sure.

**Comment by courtneypattison** [comment]
You were right about this one! pdfjs has a max area for the canvas. The reason why I could open the file with the custom renderer is because the sample custom renderer doesn't scale the viewport based on the devicePixelRatio (like the actual PageCanvas does), so it was much smaller. I found a pdfjs issue for modifying the maxArea where the poster mentioned scaling the canvas up with CSS while keeping the canvas within pdfjs's limits. I put too much into this PR but I got really excited. Pretty please check out the [preview](https://pattern-projector-git-layers-courtney-pattisons-projects.vercel.app?_vercel_share=oHdivXZxtSCYInQLCbcmkN7rXWyQ5VYn) whenever you have a chance to see if I missed something! I added a button to recenter the pattern because the patterns are so big!

**Comment by hluedeke** [comment]
Hey, I think it's great to get it done! I had not starting looking at it, so I'm happy to let you have this one :)

I hate to show you this, but this is what it did for me when I tried to open a file:


https://github.com/Pattern-Projector/pattern-projector/assets/14338579/d466b029-1c8c-4d9b-9e2b-1bbc38b8b2e1

**Comment by hluedeke** [comment]
It is doing the above behavior for any file I open, including the tried and true file I've been using for development.

On the positive side, I could not previously open that file at all, so that's progress!

PS. I think it has something to do with the CustomRenderer. Maybe that class needs to be instantiated in a useMemo or something like that? I'm not 100% sure that's the issue, but I remember running into this before, and I think it started happening when I tried to pass props down to the CustomRenderer. I am using Chrome on a Mac

**Comment by courtneypattison** [comment]
Ah drat! I knew it was too good to be true. I can’t reproduce the flickering on my computer or phone. So I’ll have to find a way to reproduce the flickering before I can debug it. I’ll definitely check out the prop passing in customrenderer.

**Comment by courtneypattison** [comment]
That would be awesome! Thank you I’ll try to reproduce and fix it tomorrow midday, but I’ll message if I find a fix. I can’t work on it tonight

**Comment by hluedeke** [comment]
Turns out I found time! All I did was convert layers/setLayers into a context provider/consumer instead of passing them through as function parameters. It works beautifully for me now!

**Comment by courtneypattison** [comment]
OMG! I just did the same thing lol. I couldn't resist either. Brought the laptop into bed.
