### ISSUE TITLE
Maximum update depth exceeded warning (cursor timeout)

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#128]
on the beta branch, I'm getting a warning when dragging the the pdf:

Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
eval	@	draggable.tsx:83
eval	@	draggable.tsx:96

It has something to do the resetIdle and handleOnMouseMove functions but I couldn't figure out how to fix it. Tried changing them to useCallback functions but that didn't seem to work.

**Comment by courtneypattison** [comment]
I can't reproduce this one.

**Comment by j-huff** [comment]
Yeah it seems to only be happening on my home Linux desktop, which is pretty slow. Maybe not a real issue?

**Comment by courtneypattison** [comment]
Maybe close for now and reopen if it causes problems in the future?

**Comment by hluedeke** [comment]
I was able to reproduce this - will look into it
