### ISSUE TITLE
Possibly change default invert colour from white to green

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#13]
Someone reported being able to see it clearer as green. In they pictures it does look easier to see. Need to test out and investigate!

Suggestion original came from [projectorsewing.com](https://projectorsewing.com/adobe-projector-patterns/). Maybe a popup when clicking the invert colors icon to choose a high contrast colour combination? Then we can start saving it in localStorage. Maybe use it for the calibration grid and invert colours?

**Comment by hluedeke** [comment]
I have an implementation for this. I'm not in love with the dropdown click event listener for the icon button. I am going to open a PR so that it builds, and you can see what I mean, @courtneypattison. It has all the functionality - it just feels kind of wrong. If you have any ideas for alternatives, I'm open to suggestions!

**Comment by hluedeke** [comment]
Let me ask this - is there a specific branch you want me to merge to, other than main? I ask this because I'm not sure we want to merge it in its current state. The test branch maybe?

**Comment by courtneypattison** [comment]
I think test branch is a good idea!

**Comment by hluedeke** [comment]
I just had an epiphany! I decided to toggle the button between 3 states: off, on, and on with green mode. That feels much more intuitive. I am going to ahead and do a PR - I can still put it into test if you want, just to test the workflow.

**Comment by courtneypattison** [comment]
I love that! If a PR is easier, just go with that.

**Comment by hluedeke** [comment]
I don't think the test branch is up to date, so GH won't even approve a merge. I'll put it to the main branch. I feel much better about it now!

**Comment by courtneypattison** [comment]
Woot woot! I'll test it out then merge :)
