### ISSUE TITLE
Add hotkeys for using the toolbar items

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#130]
E.g. r for rotate. Now that we have the useKeyDown hook from #117 i think it’s a good time to add these.

**Comment by hluedeke** [comment]
Yep! I’d even wrap the usekeydown handler in a toolbarHotkeyHandler (or something like that) hook, so it’s clear where this logic is handled. Maybe even a calibrateToolbarKeyHandler and a projectToolbarKeyHandler so it’s menu state aware? I’m not sure!

**Comment by courtneypattison** [comment]
> Yep! I’d even wrap the usekeydown handler in a toolbarHotkeyHandler (or something like that) hook, so it’s clear where this logic is handled. Maybe even a calibrateToolbarKeyHandler and a projectToolbarKeyHandler so it’s menu state aware? 

I like the idea of having one handler for calibrate and one for project! I think things are going to clean up nicely when we get those separated out a bit more.
