### ISSUE TITLE
Activating precision movement on touch/mobile is difficult 

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#132]
I'm having a difficult time activating the precision movement mode on mobile. 

It might be a better idea to use the use-long-press package instead of trying to handle it ourselves:

https://www.npmjs.com/package/use-long-press

**Comment by courtneypattison** [comment]
Looks good to me. I'd like to start using pointer events instead of mouse and touch being separated as well. I think it'd be cleaner that way. I used them for the new measure tool and they work great. I would've used them from the get go if I had known about them!

**Comment by hluedeke** [comment]
The only thing I'd say about this, and this is purely from good ol' experience:

This library isn't extremely popular, so it's vulnerable to abandonment in the future. When libraries get abandoned, they don't keep up with current node versions, they don't fix discovered security vulnerabilities, etc. That being said, this library also don't have a ton of dependencies and seems rather simple, so we're probably ok, even if the project is abandoned.

More than anything, this comment is for awareness and caution about the general mentality of using libraries for everything. The more you add dependencies, the more you have to maintain them in the future!

**Comment by courtneypattison** [comment]
Very good point! Maybe there’s a more popular library we could use or even just look at their code for guidance. I have a few published node packages and it’s outrageous how little they do but people still download them!

**Comment by courtneypattison** [comment]
Replaced with move tool in #169
