### ISSUE TITLE
Petite Stitchery patterns disappearing on rotate

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#133]
Reported by someone in Projectors for Sewing. She tried to recenter with no luck and tried on beta with the new rotate. This one is perplexing.

**Comment by hluedeke** [comment]
A little worried this could do with memory.

**Comment by courtneypattison** [comment]
Yeah, me too. They're just so big! Sasha said Petite Stitchery knows about the problem, they just haven't done anything about it yet. I tried looking using the memory profiling dev tools when troubleshooting the pdfjs maxarea issue and I was totally lost, lol. I need to learn more about using those.

**Comment by hluedeke** [comment]
I know a little but admittedly not to much, especially about the render/draw stack. This one will be hard to reproduce if it is in fact memory related. Chrome has some network throttling capabilities - perhaps it has something to force memory limits as well (to make problems like this easier to spot). We can profile memory usage (I’m also not very experienced in this), but at what point do we decide a file is “too much memory”?

**Comment by j-huff** [comment]
Do we know if it was a multipage or single page pattern?

**Comment by j-huff** [comment]
Here's a python script for generating large PDFs, may help for trying to recreate:

```
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import random
import argparse

def generate_complex_pdf(filename, num_lines, num_pages):
    c = canvas.Canvas(filename, pagesize=letter)

    width, height = letter

    for page in range(num_pages):
        for _ in range(num_lines):
            x1, y1 = random.randint(0, width), random.randint(0, height)
            x2, y2 = random.randint(0, width), random.randint(0, height)
            r, g, b = random.random(), random.random(), random.random()
            line_width = random.randint(1, 10)

            c.setStrokeColorRGB(r, g, b)
            c.setLineWidth(line_width)
            c.line(x1, y1, x2, y2)

        c.showPage()

    c.save()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate a complex PDF with random lines.")
    parser.add_argument("filename", type=str, help="Output PDF filename")
    parser.add_argument("--lines", type=int, default=1000, help="Number of lines per page (default: 1000)")
    parser.add_argument("--pages", type=int, default=1, help="Number of pages (default: 1)")

    args = parser.parse_args()

    generate_complex_pdf(args.filename, args.lines, args.pages)

```

**Comment by j-huff** [comment]
Well, it seems to handle 8 page PDFs with 100k random color lines per page alright. Maybe it has to do with PDFs with images?

**Comment by courtneypattison** [comment]
Oh my! Well that's kind of good news lol. Maybe it has to do with the layers? They have a bunch of empty layers I think. I have one of their freebie patterns and it's 2 pages 1.7mb. One of the characteristic things about their patterns is that the width/height is over 200 inches. Someone in Projectors for Sewing contacted them last night and they are going to stop making them so wide going forward! Doesn't help with the back catalog though.

**Comment by hluedeke** [comment]
> Edit: Seems to handle 8 pages of 1000 lines + 1000 images fine as well... 40MB pdf lol. Are their PDFs larger than that?

That's insane, haha. But also, how beefy is your computer? I'm on a pretty recent apple M series chip with decent memory, so I know my computer can handle a lot of things. I also know that there are people out there using really old and far less powerful computers and tablets. This may not be sufficient as an argument, especially after seeing the massive size difference between your file and the PSco one. But it's something to at least consider.

It'd be nice to get the actual file to test with, but I understand copyright and all that.

**Comment by hluedeke** [comment]
> Someone in Projectors for Sewing contacted them last night and they are going to stop making them so wide going forward!

That'd be amazing!

**Comment by j-huff** [comment]
>  But also, how beefy is your computer? 

My Linux machine is a mid 2000s mid range Intel with 8GB RAM. Graphics card struggles to draw the canvas when I have it full screen at 1440p. So not very beefy at all lol.

**Comment by courtneypattison** [comment]
It’s the Jo dress pattern. I was thinking about buying it then mangling it with pdf-mangler and sharing it. It’s a cute pattern lol. I’ll probably do that tomorrow when I can sit at my computer.

**Comment by courtneypattison** [comment]
#135 and #148 fix this issue.
