### ISSUE TITLE
Unable to close stitch menu after opening single page PDF

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#134]
If you open a multi-page PDF and open the stitch menu, if you then open a single page PDF the icon button for "hide stitch menu" goes away but the menu is left open, unable to be closed unless you refresh or open a multi-page pdf again. menu should be closed automatically if the open/close stitch menu button is hidden.

**Comment by courtneypattison** [comment]
Whoops! I'm not sure about automatically hiding it though. Then they can't open it again. Might be annoying if you're only trying to look at one page at a time. Maybe we should always show the stitch menu but have it be disabled when there's only one page?

**Comment by hluedeke** [comment]
Here's a test if the page count changes: if page count is 1, hide the menu. otherwise, if the page count is more than 1, set it to open by default. I think that's what we're going for, correct?

**Comment by courtneypattison** [comment]
Sorry, I missed a word in there! I meant always show the stitch menu button not the whole menu.

I think the flow you mentioned works @hluedeke!

**Comment by hluedeke** [comment]
Ok, I have it on a new branch I'm working on right now 👍
