### ISSUE TITLE
Grid is not visible on computers with multiple screens

### ISSUE THREAD

**Issue by hluedeke** [Pattern-Projector/pattern-projector#15]
With computers that use multiple screens, the grid jumps out of the field of view, probably because the initial grid coordinates are calculated off of screen size.

This was reported by a Facebook user and confirmed on my machine with a secondary monitor hooked up.

**Comment by courtneypattison** [comment]
What about using [window.screenTop](https://developer.mozilla.org/en-US/docs/Web/API/Window/screenTop) and window.screenLeft to set the defaults based on viewport instead of screen?

**Comment by hluedeke** [comment]
So I tried window.screenTop and window.screenLeft, but they have the same problem that window.screenX and window.screenY have.

I'm curious what the purpose of the following code is from page.tsx, lines 129-133:

```
  useEffect(() => {
    const dy = windowScreen.y + window.outerHeight - window.innerHeight;
    const dx = windowScreen.x + window.outerWidth - window.innerWidth;
    setCanvasOffset({ x: -dx, y: -dy });
  }, [windowScreen.x, windowScreen.y]);
```

Was this to maintain the same location of the grid regardless of where the browser was on the screen?

If I set the canvasOffset to: ```setCanvasOffset({ x: 0, y: 0 });``` the issue goes away.

**Comment by courtneypattison** [comment]
Yes, that exactly it. Except it doesn’t work well because some people have toolbars to the right or bottom. I was trying to stop the grid from moving when toggling full screen. Also, if someone moves their browser window. I’m not sure if it’s possible to reliably set the grid based on screen coordinates.

**Comment by hluedeke** [comment]
Here's what I'm thinking about that. Intuitively, I know there's a difference between full screen and non-full screen.I think most people will use fullscreen when calibrating/projecting, as it's the easiest. Even when it exits fullscreen to open a PDF, I immediately set it back to full screen to project (the calibration grid did not stay in the same place on my computer between full-screen and normal window).

I say we remove the complexity and just use the default offset. Let's make things easier on ourselves 😅 it's fast enough to recalibrate that even if this becomes an issue, I think it's only a minor issue at best.

**Comment by courtneypattison** [comment]
I think you're totally right! I just overcomplicated things out of a fear of someone not realizing their calibration was off but people seem very careful about that and always have a calibration square in sight. It's not working anyway!

**Comment by hluedeke** [comment]
I've fallen victim to overcomplicating things more than I can count 😂 so you are in good company! I'll get this one knocked out and PR it here soon.
