### ISSUE TITLE
Stitch menu resets PDF location with each setting change

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#150]
Now that the transform origin in set to center, the stitch menu resets the location of the pdf whenever there is a setting change.

**Comment by courtneypattison** [comment]
@j-huff what do you think about this one? I’m thinking about switching the transform origin back to the top left. The switch menu feels quite frustrating now.

**Comment by j-huff** [comment]
Right, it's set to recenter whenever the layout changes. So if you go from show 1 page to 2 pages it recenters, or if you change the number of columns. I can remove that if it's annoying.

**Comment by j-huff** [comment]
Since when is it unreasonable to expect users to understand greek alphabet math notation? 🤔

I'll think of something. Also I'm going to add drag grid snapping to this PR as it seems natural as the position gets displayed as fractions only if you are on the grid.
