### ISSUE TITLE
Add arrow key movement alternative for touch

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#157]
For touch/mobile, it would probably be good to add an alternative method of moving the PDF by a known amount, like how arrow key movement works on desktop.

I'm thinking maybe tapping the PDF will toggle on screen arrow buttons possibly? Could have toggle off automatically after a few seconds of no use if the user doesn't know how they turned them on/how to turn them off (just tap the PDF again).

**Comment by courtneypattison** [comment]
Added in #169!
