### ISSUE TITLE
Grid calibration corner hotspots are not correct in fullscreen mode

### ISSUE THREAD

**Issue by hluedeke** [Pattern-Projector/pattern-projector#16]
In regular screen mode, the handles are clickable and work great. In fullscreen mode, however, the hotspots are not over the corners of the grid, making it hard to locate the corners to drag.

The viewport to screen coordinates probably change and are not accounted for. This can probably be addressed at the same time as the multiple screens bug (#15 )

**Comment by hluedeke** [comment]
Ok, so I just tested this locally...and it was not off. I refreshed patternprojector.com and tried again, and...it wasn't off.

So, I'm not sure if this is in fact a bug or not. I do think this might be an edge case, but I haven't figured out exactly what I did to cause it. Maybe I should try it again with the projector plugged in 🤷‍♀️

**Comment by courtneypattison** [comment]
I’ve definitely had this happen to me! Refreshing has worked in the past for me as well. I’ve just been ignoring the bug. Thank you for reporting!

**Comment by hluedeke** [comment]
Would you mind if we created a new label for "needs more info"? We have this tag at work, and it's helpful to see when next to a "bug" label so I know I can skip it when bug fixing ;)

**Comment by courtneypattison** [comment]
That's a great idea! Done :)

**Comment by courtneypattison** [comment]
I think this issue was coming up due to my failed attempt at making the grid corners screen coordinates. I haven't noticed this since you pushed that update. Have you? I'm feeling ready to close this one.

**Comment by roel-v** [comment]
I saw this too last week but not since then.

**Comment by hluedeke** [comment]
Same here! Haven’t seen it 👍
