### ISSUE TITLE
Should we add a build version number?

### ISSUE THREAD

**Issue by hluedeke** [Pattern-Projector/pattern-projector#18]
Should we add a version number on the top toolbar so users know what version/build number they are using when reporting issues? This will be helpful for people who have the application downloaded, and it will also help users know when we've made updates.

Thoughts?

**Comment by courtneypattison** [comment]
That’s a good idea. There’s also the option to prompt the user to update when a new release is available. https://github.com/DuCanhGH/next-pwa/blob/master/examples/lifecycle/components/PWALifecycle.tsx#L20-L40  It only takes them closing and opening the app or refreshing the page to trigger downloading the new version.

**Comment by hluedeke** [comment]
@courtneypattison well that takes care of the offline folks! It does seem like savvy folks would pick up on a version change and could mention failures more accurately, but it also requires us to come with a versioning scheme 😅 so I'm ok leaving this one for now. Just wanted to throw the idea out there!

**Comment by courtneypattison** [comment]
Maybe we could just ask them to refresh the page when troubleshooting if it seems like their problem is from an older version for now. Especially since the offline functionality isn't enabled yet.

**Comment by courtneypattison** [comment]
Added in #175 with changelog
