### ISSUE TITLE
Add a keyboard shortcut to blank the screen

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#184]
I would like to be able to blank out the screen (have the entire screen be the color of the background of the current color palette), for example with the keyboard shortcut 'b'. As I was cutting and marking, which I have to do in low light circumstances because my projector isn't very bright, I often wanted to double check e..g how sharp my corners were. Turning off the projector is very annoying because it requires you to reconnect. So I resorted to holding a book in front of the lens, but that wasn't very convenient either.

When the 'blanked screen' is on, it should probably show a permanent (non-dismissable) message a the top that says 'screen blanked, press b to re-enable' or something like that, because people *will* hit it by accident and freak out. The state should probably not be stored in the settings either, so it's forgotten about upon reload.

**Comment by courtneypattison** [comment]
I’ve been trying to think more mobile first this week and I’m not sure how this feature would translate to tablets. I’m also not positive I’m understanding correctly to try to think of another idea! Are you trying to check how nice your last cut is but the lines of the pattern are blocking being able to see the cut? Would toggling to light mode be enough to be able to see the cut better?

Have you tried turning down the brightness on your projector, then crank up the contrast? It’s an unintuitive change but made a big difference with my setup. Less illumination on the black.

Maybe for now a hotkey that hides everything only when it’s held down?

**Comment by roel-v** [comment]
Yes what you describe is the use case. Things like 'did I cut all the way into the corner', 'did my chalk take well enough on this notch mark I just did'. Switching color scheme didn't make it as clear as I would have liked.

Having it be a hotkey that only works while being held down has the same disadvantage as my book workaround - if the keyboard is a bit away from the cutting area, you can't both have you nose on the fabric and still reach the keyboard. And the reason I would like this to be a hotkey is that this toggling happens often and in quick succession.

I guess the behavior I'm looking for here is really a shortcut for toggling the 'disabled' state of the 'overlay options' menu. 'Disabled' is already a bit of an outlier in this menu, since conceptually that menu is a hierarchical mutually exclusive option list with 'disabled' and 'enabled' states, and then 'enabled' having different multiple select sub states. (I really enjoy how this menu is flattened into a 1D list with the others greyed out; this feels very natural and it only becomes obvious that this is actually quite a complicated interaction once you start analyzing the way I was doing trying to understand my own request better.)

Anyway so in that sense, it's nothing special for mobile; like the other keyboard shortcuts, it's irrelevant on mobile, you just have to use the toolbar menu.

**Comment by courtneypattison** [comment]
I cut a pattern on Sunday and didn't make it through both layers. Then I couldn't see the cut line because of the line from the projection so I totally get where you're coming from on this one now. I don't think it makes sense in the overlay options because the PDF isn't an overlay but I do think we should add this functionality in. I may try working on the menus this week and see what I can come up with.

**Comment by roel-v** [comment]
Yeah you're right, it has nothing to do with overlay, I'm not sure what I was thinking when I wrote that.

**Comment by courtneypattison** [comment]
I'm going to close this issue as wontfix. I think the magnify tool mostly fixes this issue. You can press M or click magnify, then click on an empty part of the pattern and the screen will be mostly blank depending on your pattern.
