### ISSUE TITLE
Change mouse cursor when it gets to areas where drag action can be performed

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#194]
(irrelevant for mobile)

Right now, when you move your mouse cursor, the visual cue that you can do something is that the element under the cursor (circle for corner, single edge line for moving edges, all edges for moving raster) changes styling to a dashed line. I think it's consistent with other user interface elements to (in addition to this change in styling) change the cursor to a diagonal one for the corners, left/right for edges, four arrows for moving the grid.

Maybe I'm mistaken but didn't it used to work like this before the new dashed-line styling was introduced? If yes then there probably was a reason to remove it, but it feels off to me now...

**Comment by courtneypattison** [comment]
This was removed by accident during the big calibration code overhaul! Whoops. I'll add it back.
