### ISSUE TITLE
Add internationalization

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#2]
[NextJS internationalization](https://nextjs.org/docs/pages/building-your-application/routing/internationalization)
German and Danish requested.

**Comment by courtneypattison** [comment]
I added support for internationalization to branch intl. It still needs to be checked over though! A couple of volunteers are working on the translations.

**Comment by hluedeke** [comment]
Open a PR if you're ready for a code review! A PR highlights the code changes quite conveniently :)

**Comment by courtneypattison** [comment]
Done! Thank you :)

**Comment by roel-v** [comment]
Is there a language switcher widget somewhere that I'm missing? Or how does it decide what localized url to redirect to?

**Comment by courtneypattison** [comment]
Yeah, sorry, the [] is for nextjs magic routing. I love visual studio code. I used vim throughout school and switched to visual studio code when I started doing web development. I think my .vscode file is in this repo. I should really remove that!

**Comment by roel-v** [comment]
OK thanks, I was just wondering.

I do use Visual Studio as my IDE for C++ development but for small projects on the side like this I start out with my regular vim editor that I've been using for a long time. It does open the file when I open it from a file explorer, it's just that the file explorer built into vim doesn't show any contents for that directory. Now that I know I can pay attention to it.

**Comment by hluedeke** [comment]
Ok, got it 👍

> it's just that the file explorer built into vim doesn't show any contents for that directory.

I didn't even know vim had a file explorer!

> but for small projects on the side like this I start out with my regular vim editor that I've been using for a long time.

I always find it interesting how different people program in different ways. Depending on how you start (or even when you start), it can be totally different.

**Comment by courtneypattison** [comment]
Lol, I chose NextJS on a whim instead of picking the right framework for the project. Now we're living with the fallout!
