### ISSUE TITLE
Add an annotation/tag for shifting pattern

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#200]
Someone from the group wants something to tag a spot then shift the patter/fabric when the piece is larger than the projection area. I made the measure tool keeping this sort of functionality in mind. I was thinking maybe dual purpose it by having the measurement move with the pattern. Is that too undiscoverable? Separate button for marking a spot? Something else?

**Comment by courtneypattison** [comment]
Doodle overlay? A few unique shapes scattered around the viewport that move with the pattern, making landmarks to go by.

**Comment by sashasewist** [comment]
> Someone from the group wants something to tag a spot then shift the patter/fabric when the piece is larger than the projection area. I made the measure tool keeping this sort of functionality in mind. I was thinking maybe dual purpose it by having the measurement move with the pattern. Is that too undiscoverable? Separate button for marking a spot? Something else?

You have mae a measure tool? I will check this out, have not seen it. Making that tool dual purpose sounds interesting. I will report back later after testing.

**Comment by sashasewist** [comment]
I tried your measure tool, very nice!! Would be nice to have it be a 3 stage toggle:
- click ON, and mesure tool is active and shows measurements 
- click again and measurements are hidden but measured lins stay
- click again and both lines and measurements are hidden/OFF
- click ON and they come back.
It would be nice if the pattern could be scrolled when in measuring mode (and yes marks stay in same location on off). not just for when needing landmarks for shifting fabric, but also when measuring multiple parts of pattern pieces we need to scroll.
I found this icon that has ruler and pencil, but scale is likely not right for visibility in PP toolbar:
https://thenounproject.com/icon/ruler-5088326/

**Comment by courtneypattison** [comment]
I like that idea! I’ve been thinking something of something similar. I at least want the lines to stay with the pattern when moving. I think having the different modes would be a great solution.

**Comment by courtneypattison** [comment]
I'm getting excited about this one lol. We use material icons in PP. I found one similar to the one you found https://fonts.google.com/icons?selected=Material+Symbols+Outlined:design_services:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=pencil

I'm thinking draw whatever lines you want and they stay on the pdf and move with it even when the measure tool isn't activated. Click on a line and it'll show context for that line like length, angle, rotate to horizontal button, and delete button to get rid of the line.

**Comment by sashasewist** [comment]
Sounds perfect! 👍🏻
