### ISSUE TITLE
Add tooltips for icon buttons

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#21]
Maybe on hover show a tooltip showing what the icon buttons do. I’ve gotten a few messages where people aren’t sure what they are for e.g. “ I'm trying to delete a projection and start over, but I can only move the current grid. Is there a way to delete and start over.”

**Comment by hluedeke** [comment]
Yes! I was totally planning on throwing this in at some point!

I think we should create an IconButton component. I've already created a Modal component and a Button component that support multiple styles and colors. I can put up a PR with that code, but it's currently not really in use because I built it to support the error dialog.

You can add a Tooltip component as well, that I believe will wrap the IconButton component.

**Comment by courtneypattison** [comment]
Agreed! That's exactly what I was thinking :) I've just been putting it off, lol. So much to do!

**Comment by courtneypattison** [comment]
That looks great! It's nice to finally be moving theming to one spot. I'll just make a tooltip component to wrap the button component.

**Comment by courtneypattison** [comment]
I'm just going to throw this here for now. Then I'm thinking after you merge #14 we can do a nice refactor and clean up the header!
```
import { ReactElement } from "react";

export default function Tooltip({
  children,
  description,
}: {
  children: ReactElement;
  description: string;
}) {
  return (
    <div className="relative flex flex-col items-center group">
      {children}
      <div className="absolute top-7 flex flex-col items-center hidden mt-6 group-hover:flex">
        <div className="w-3 h-3 -mb-2 rotate-45 bg-black"></div>
        <span className="relative z-10 p-2 text-xs leading-none text-white bg-black rounded text-center">
          {description}
        </span>
      </div>
    </div>
  );
}
```

**Comment by hluedeke** [comment]
Ok, I’m thinking about “won’t fixing” #14 and just doing a component-only commit. The pop up is a little too noisy. I can get that done at some point today, probably in the afternoon or evening.

**Comment by hluedeke** [comment]
Where did we end up with this? Are you still working on it @courtneypattison? Or would you like me to look at it?

**Comment by courtneypattison** [comment]
Sorry, I got sucked into the layers and size issue and totally forgot about this. If you’re interested, please do look at it!
