### ISSUE TITLE
Full Screen Project Not Working

### ISSUE THREAD

**Issue by icybabybows** [Pattern-Projector/pattern-projector#213]
Hi! I really needed to cut out some fabric today and the full screen on project mode isn't there. It shows on calibrate but not project.

**Comment by courtneypattison** [comment]
I'm so sorry about this issue. If you go to https://beta.patternprojector.com/ It should be fixed. Please let me know if that works for you.

**Comment by icybabybows** [comment]
thank you! will I have to use that one from now on?

**Comment by courtneypattison** [comment]
You're welcome! No, I should have the fix out to the main site tonight. Just finishing up testing before sending it out.

**Comment by courtneypattison** [comment]
Fixed #214
