### ISSUE TITLE
Add diagonal measurement to calibration

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#218]
As per Sasha's suggestion in #203. I'm thinking maybe a modal that shows a few common scenarios for incorrect calibration, e.g. a image of an off by 1 width/height and bent lines from an uneven table/mat.

**Comment by hluedeke** [comment]
Another one to throw in here (I think): What if we showed a warning if the calibration grid coordinates don't make sense?

Eg: if someone enters 16in x 24in, and the 16in side is actually longer than the 24in side in actual coordinates, that would generate a warning (maybe take the average of both vertical edges and both horizontal edges to get the comparison value). If they enter 16in x 16in then there would never be a warning.

**Comment by courtneypattison** [comment]
> What if we showed a warning if the calibration grid coordinates don't make sense?

I've been thinking about this one as well! I'm hesitant to put warnings because they send people into a panic but I think if it were well tested and only showed up in cases where we're pretty confident the numbers are off it'd be helpful rather than stressful. I don't usually input my width and height until after I've matched up my corners.

**Comment by renatosc** [comment]
I am interested on being able to have fine tune calibration (maybe by adjusting individual points) to account for uneven/warped mat/table as suggested by this issue. I see that this issue is closed but I don't think we have a way to do that right? If not, I can work on it and make a PR for y'all.

**Comment by courtneypattison** [comment]
Hi @renatosc ! Thank you for your interest in contributing to PP! We don't plan on supporting uneven/warped surfaces in PP. A warped mat will often be flattened when cutting with a rotary cutter so I recommend finding an even surface or making the surface even with card-stock etc instead of a software solution.
