### ISSUE TITLE
[Feature] Allow save/load calibration config

### ISSUE THREAD

**Issue by shiltox** [Pattern-Projector/pattern-projector#229]
## Target
- GUI user

## Use cases
- For static setup, recalibration every time is time consuming.

## Feature description
- Current: User needs to use GUI to calibrate every time
- Proposed: 
  - Option1: Enable user to download/upload json config of the current calibration config

  ![Untitled Diagram drawio (3)](https://github.com/Pattern-Projector/pattern-projector/assets/37970714/6c876be6-9a89-445d-8b61-fa49e17d8b0e)

  - Option2: a form data for the 4 local points of calibration screen)

  ![Untitled Diagram drawio (1)](https://github.com/Pattern-Projector/pattern-projector/assets/37970714/abb60915-3171-4ffc-aaef-3395cc7eb7e2)

This is just a concept. Feel free to change the implementation.

**Comment by sashasewist** [comment]
there shouldn't be any recalibration needed. calibration is auto saved (in same browser0. sound alike that's not happening for you?

**Comment by shiltox** [comment]
@sashasewist Nice. I tested with no-cached browser.

Then this issue won't be needed. You can close this issue when you see fit.

**Comment by shiltox** [comment]
@sashasewist Nice. I tested with a no-cached browser back then.

I retest with normal browser and it does work as expected.

You can close this issue when you see fit.

**Comment by shiltox** [comment]
Close because not needed. See https://github.com/Pattern-Projector/pattern-projector/issues/229#issuecomment-2068053739

**Comment by courtneypattison** [comment]
@shiltox thank you for letting us know!
