### ISSUE TITLE
Align to vertical/horizontal or make right angle when calibrating

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#231]
Suggestion from Projectors for Sewing: add an option to snap point to match horizontal/vertical of point that is correctly located. I was thinking maybe something like a make me a right angle option in a context menu. Then you'd only have to drag two opposite corners and snap to right angle to calibrate an already calibrated setup. Not sure how to make this intuitive/easy to understand without cluttering up the UI though.

**Comment by sashasewist** [comment]
I remember seeing that comment and thinking the person wasn't understanding how PP worked.
Right angle is real life/projected lines can't be known by PP.
PP can only know when screen angle is 90 degrees. But having a right angle on screen has no value if calibration not accurate with right angle on screen.
And the way to if projected/real life angle is 90 is to compare it to grid, or if no grid then just to piece of office paper.
I think the way PP now allows moving sides is the solution for this person. She wanted to square up projection, so moving sides of PP will be best way of having a "square" calibration where adjustments are made in real life to square up projection.

**Comment by courtneypattison** [comment]
Someone from the group emailed me with this suggestion. I think their main motivation is trying to save time by having to align fewer corners with an already calibrated setup. I agree that dragging sides takes about the same amount of time so it's probably not worth it to add this feature. I'm thinking drag the whole grid to one corner, then drag the other two edges and you're done.
