### ISSUE TITLE
Should there be a recommended browser?

### ISSUE THREAD

**Issue by sashasewist** [Pattern-Projector/pattern-projector#232]
I'm thinking of updating the one page guide
https://bit.ly/onepageguidetoprojectorsewing
to recommend using Chrome with PP? Does that make sense? So new users start with best environment?
Here's my wording so far:
"**Pattern Projector** A web-based, free, open-source tool by Courtney Pattison.  Using Chrome browser will work best in most cases.. Available at: **[www.patternprojector.com](http://www.patternprojector.com/)**"

**Comment by sashasewist** [comment]
I could also add "Can also be used offline" - would that be helpful, or too much info for intro guide?

**Comment by sashasewist** [comment]
Maybe "Using Chrome browser will work best on most devices" instead.

**Comment by courtneypattison** [comment]
Yeah, agreed! I'd like to add that to the landing page documentation as well. Edge is good, Firefox is ok, and Safari is horrible. 

Maybe leave off the offline support for now until I get #210 done. Right now it's hard to tell when the app is ready to be used offline.
