### ISSUE TITLE
Feature Request: Unfold 'cut on fold' patterns

### ISSUE THREAD

**Issue by myogpatterns** [Pattern-Projector/pattern-projector#236]
Add ability to select a pattern element and "unfold" by mirroring and aligning to an edge.

**Comment by courtneypattison** [comment]
There’s similar functionality in PP! If you open up the overlay options (grid icon in the menu) press the flip lines then line up your fold edge on one of the red lines and the flip will happen across that line. PP always flips across those lines even when they aren’t shown. Does that work for you or are you looking for something else?

**Comment by myogpatterns** [comment]
Oh wow! I totally missed that feature with the overlay. That worked perfectly and is a much simpler user interaction than I had in mind. Thanks for your explanation!

**Comment by courtneypattison** [comment]
Awesome! Don't hesitate to fire off any other feature requests. It's great having someone else in the repo :)
