### ISSUE TITLE
Tab through corners

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#28]
Be able to tab through the calibration corners. A nice little power user extra?

**Comment by hluedeke** [comment]
Yes!! Was totally thinking this!!

**Comment by hluedeke** [comment]
I'm going to add "changing the color of each corner" as well. Someone mentioned that on the FB to figure out which corner they were dealing with more easily. Especially with tabbing, I think this will be nice.

**Comment by courtneypattison** [comment]
Agreed :)

**Comment by hluedeke** [comment]
I'd like to get an icon for an IconButton that toggles "4-corner mode". I'm not sure where you are getting icons from, but do you think you could find one that's appropriate? The rest of the functionality is there. In my current branch, it's activated via Shift+Tab, but that's not obvious unless you know it's there.

**Comment by courtneypattison** [comment]
They're all from https://fonts.google.com/icons That's a tricky one to think of though!
