### ISSUE TITLE
Add layer toggling

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#29]
I'm going to start digging into this. I'll document any perceived progress I've made here!

**Comment by hluedeke** [comment]
https://github.com/wojtekmaj/react-pdf/blob/main/test/CustomRenderer.tsx

^ That is what I used for the CustomRenderer. It isn't perfect, but the author suggested using that as a starting point for custom renders.

**Comment by courtneypattison** [comment]
Hmm, would you feel comfortable making a PR with what you have?  I could make an experimental branch or something? Then I can see if I can help clean it up. I didn't realize what a messy file format PDF is until working on this project.

**Comment by hluedeke** [comment]
I have made a PR for this, as you've probably seen. I have since discovered a render() function on PDFPageProxy that *might* mean we don't need the custom renderer.

**Comment by courtneypattison** [comment]
Oh darn, that's disappointing. I haven't had a chance to look at it yet but I'll check out the PR tomorrow and see if a pair of fresh eyes helps!

**Comment by hluedeke** [comment]
@courtneypattison for sure! I'm done looking at it for now 😂
