### ISSUE TITLE
Add some place in the documentation to point users to localized community resources

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#33]
I've seen Pattern Projector come up a few times in Dutch projector sewing Facebook groups already. It would be nice if the documentation had some place where such resources can be linked to. Each translator can then collect all resources in 'their' language translation. This would require some way to have bulleted lists in translations, of which the translator can decide how many bullets there should be; is that possible?

**Comment by courtneypattison** [comment]
Sorry, I missed this one! I think that's a great idea. It's possible to [create variable length lists using next-intl ](https://next-intl-docs.vercel.app/docs/usage/messages) which is the library PP is using. So maybe another header "Additional Resources" or something like that with a list of links and names.

```
{
  "Resources": {
    "projectorsForSewing": {
      "title": "Projectors for Sewing",
      "link": "https://www.facebook.com/groups/481078582801085"
    }
  }
}

import {useTranslations, useMessages} from 'next-intl';
 
function CompanyStats() {
  const t = useTranslations('Resources');
 
  const messages = useMessages();
  const keys = Object.keys(messages.Resources);
 
  return (
    <ul>
      {keys.map((key) => (
        <li key={key}>
          <a href={t(`${key}.link`)}>{t(`${key}.title`)}</a>
        </li>
      ))}
    </ul>
  );
}
```
