### ISSUE TITLE
Hard finding spot in PDF with large margins

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#36]
From someone using the website: "Would it be interesting to have a small scale preview in a corner, showing you where you are in the document? You know, like a small rectangle and a red dot or something representing the mouse and its position on the canvas. I cut my first project today, using this tool - 1/4 of the patern had no pieces, all was white, I had no idea where I was. With Adobe, I zoom out, move the page, and then zoom back in. "

I'm thinking maybe for now it might be easiest to at least open the pdf so the transform origin is centered with the calibration grid so at least you start in the middle. Thoughts?

**Comment by hluedeke** [comment]
Sure! It does seem like most pattern pieces would be centered, so this approach makes sense to me.
