### ISSUE TITLE
Move PDF with arrow keys

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#37]
Suggested by someone using the website. I like this idea. Not sure how big the jump should be for one click though.

**Comment by hluedeke** [comment]
What if we did a progressive jump? For the first 2 seconds, only 1 pixel at a time. After 2+ seconds, 10 pixel jump...and on and on up to, say 250px or something. When the user keys up, reset it to 1px.

I'd be willing to look at this one! I was already thinking about trying it for the calibration grid.

**Comment by courtneypattison** [comment]
Ooo that would feel satisfying.
