### ISSUE TITLE
Fix scaling on large illustrator files

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#46]
From Sasha: "Inkscape doesn’t make scaling changes unless we deliberately do so. It’s AD that it’s easier to accidentally change scale because changing paper size changes scale unless we check a specific option (“anchor to page”) to prevent that.
But the issue that is happening with some pattern projecting much smaller is not related to Inkscape or AD at all - it comes from files created by Adobe Illlustrator that are over 200” and Illustrator applies a 10X compression to these files. When these files are opened in Adobe acrobat, it knows about this and returns file to regular scale. But non Adobe software like yours, or pdf stitcher, Insckape, AD, etc don’t know about this compression so scale remains 10x smaller. Solution for PP is to tell people for these files to adjust calibration by 10x - for example instead of entering 24”x36” in the calibration screen enter 2.4” and 3.6” but still make that projected distance match 24x36” on the mat. That will increase the scale by 10x on these files and they will project at accurate scale. Double check of measuring projected test square will verify accuracy of this method.
The main designer than has this problem is files from Petite Stitchery (PSCo), but occasionally I have seen this problem with Chalk and Notch, I think and one other I can’t recall."

**Comment by courtneypattison** [comment]
Agreed! At some point we can see if we can see if we can detect it from the metadata or something

**Comment by hluedeke** [comment]
Oh this is very beautiful. Thanks for sharing this! And thanks for coming to say hi! I've considered more than once trying to get your attention in the group to ask PDF questions ☺️

**Comment by courtneypattison** [comment]
Thank you so much @cfcurtis! I've also considered messaging a few times but felt too shy about it.

**Comment by hluedeke** [comment]
I'll take a stab at this one tonight

**Comment by courtneypattison** [comment]
Thank you Hannah :) I'm going to be a little checked out over the next few days. It's about 8 weeks before the average last frost date here, so I need to get my seedlings started if I want fruit and veggies in the garden this year!
