### ISSUE TITLE
Keyboard handling: keyboard movement of selection doesn't work upon page load

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#48]
Right when you get to the 'calibrate' page, be it after clicking 'start calibration' from the main page or when you ctrl-r page reload, there is a selected corner (either one corner has a larger circle or one circle is showing depending on the state of the 'show all corners' selector at the top), but nothing happens when you press any keyboard arrow key. Only after clicking on the circle again does it start moving with arrow presses.

Latest Firefox on Windows 11 FWIW.

**Comment by courtneypattison** [comment]
Good catch, I think maybe the calibration canvas needs to be focused first.

**Comment by hluedeke** [comment]
In the better-key-management PR, this should be fixed.

**Comment by courtneypattison** [comment]
Awesome!

**Comment by courtneypattison** [comment]
I’m going to try to merge that PR with layers today and get deploy it.

**Comment by hluedeke** [comment]
Good to close?

**Comment by courtneypattison** [comment]
Yes! Thank you!
