### ISSUE TITLE
PDF Page switching: give visual cue that user is on the first/last page

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#49]
The back/fwd buttons on the page switching tool don't change color to indicate when 'back' is unavailable (when on the first page) or 'fwd' is unavailable (when on the last page). The mouse cursor does turn into a cursor to indicate the widget is no longer clickable. To make things consistent with how disabled widgets tend to work, the icon needs to switch to a 'dimmed' state, e.g. to a lighter grey color.

**Comment by courtneypattison** [comment]
That's a good idea!

**Comment by hluedeke** [comment]
I'm gonna knock this one out in the tooltips branch, since I will be refactoring the header component anyway.

**Comment by courtneypattison** [comment]
I’m so excited to see it refactored! Thank you!
