### ISSUE TITLE
Allow setting subdivisions in calibration raster layout

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#60]
So I've been setting up my projector setup anew this weekend, in a more permanent way. I  have what is probably the most pathological setup that is possible; see pictures below. Not only is my projector mounted off-center in both X and Y axis directions (by an extreme amount in the X), it is also rotated around the Z axis (although I will print a new, hinged mount for my projector so I can fix this last issue in meatspace rather than software) and the Z distance (i.e. distance between lens and cutting mat) is only just within the manufacturer recommended distance, and then only because I project at an angle. And all of this with a 80 euro Yoton Y3 projector.

Despite all of that - it works great! The projection matrix is so extreme that I have to go into full screen mode to be able to move my top left corner enough (look at the distortion in that last pic down below!), but when I do that it's all spot on! And the moving of the corners with the keyboard arrows and tab works just *chef's kiss*. Great job. This is going to open up a lot more choice in projectors for people, this literally enables things that weren't possible before, not just 'makes things easier'.

Anyway, my setup involves an Ikea tabletop fixed onto an Ikea convertible couch/bed using 3d printed brackets (my 'sewing room' is really a half finished attic room that doubles as a guest room). This table top is awkwardly sized for cutting mats, at least for cutting mats big enough to cut an entire cloth width (1m40) at once; so what I did instead is order a custom sized cutting mat that is 1m80 wide and 60cm high. Because I don't have a grid on this cutting mat (it's transparent), I used masking tape underneath the cutting mat to draw a 80x40 cm rectangle on it, subdivided every 20 cm horizontally and every 10 cm vertically. Now, I can enter 80x40 in the raster size in PP, but then I get grid lines every centimeters (see pic 2 below). It would be nice to have some way to make a coarser grid.

There are several ways to go about this, including one where you can specify in each direction every how many units you want a line, but I think this makes the UI much more complicated than need be. If there were one more unit in the unit drop down, dm (decimeter), then the logic could still be that it draws grid lines on every unit, but when dm is selected (in my case I would then fill in 8 in the width and 4 in the height), that would mean a grid line every 10 cm.

This way it would not be possible to have custom distances like every 5 or 20 cm or every 3 inch or whatever, but I think this is a fair tradeoff against how much this will complicate the UI. For people like me who calibrate on their own reference grid, having a line every centimeter is too much, but 10 cm seems like a workable amount.

![2024-03-03 15 46 43](https://github.com/Pattern-Projector/pattern-projector/assets/568567/8027959e-96ee-45d7-bbb3-add0afe4abcc)
![2024-03-03 15 46 53](https://github.com/Pattern-Projector/pattern-projector/assets/568567/95208418-d914-4970-860b-3138d9908d40)
![2024-03-03 15 47 00](https://github.com/Pattern-Projector/pattern-projector/assets/568567/9e9fb1cf-018e-4e6d-b2ab-a568c606744c)

**Comment by courtneypattison** [comment]
Woot woot! Your setup looks great!

I’m not sure about dm. I feel like that one could confuse people. What about something like major and minor lines. Like thicker lines every 10cm/5 inches or something like that? That sort of scheme seems common on mats.

**Comment by hluedeke** [comment]
> What about something like major and minor lines.

Was exactly what I was thinking.

@roel-v that’s pretty awesome. What a cool testament to the capabilities of this tool! This is why I love software development.

**Comment by roel-v** [comment]
Yes I thought about major/minor at first too, but I'm not sure having the major ones wider is as comfortable when calibrating, as then you start to have to line up the middles of two lines rather than the lines being narrow enough to not really have a width at all, if that makes sense. And having the minor lines be a lighter color than the major ones risks them not being visible enough at all. Do you use the minor lines when calibrating, or are they there more to make the projected pattern look like the cutting mat as much as possible? If it's only for the 'feel', maybe the minor lines not being all that visually when you focus on them isn't a big deal. I was thinking about it, and I think I prefer the look and feel of the 'fully' filled in grid (i.e. minor lines showing, or at least a hint of them), even if those lines aren't really actively used when calibrating.

Or if we can afford another toolbar button, it could be one that toggles the minor lines color state between full color (i.e. same as major)/lighter color/off, maybe with the default being 'lighter'?

**Comment by courtneypattison** [comment]
I made a PR with major and minor lines because I think this one is best tested out to see if we like it. I'm having a hard time knowing if I'd want thicker lines or not. I don't have time to check with the projector this morning but maybe I'll cut something later today and see how it feels. I really like having all the lines because when you're calibrating on a mat with grid lines and get it just right, there a *shing* moment when everything lines up perfectly that I love. Lol, shing is probably not the best word but I'm not sure how to describe it. https://pattern-projector-git-lines-courtney-pattisons-projects.vercel.app/en/calibrate Let's see if we like this and if it's no good we can consider adding in the toolbar button as you suggested.

**Comment by courtneypattison** [comment]
Sorry, I forgot to change the settings! https://pattern-projector-git-lines-courtney-pattisons-projects.vercel.app?_vercel_share=NcPMXWMwj5AsVdVhf6xlifGA7d6gUnX5

**Comment by roel-v** [comment]
Just tried it on my setup:

- Was the green-on-black during calibration already there yesterday? I'm not a fan, I much prefer black on white, but I have a black on white reference grid, whereas I assume you (and most others) have a black on green cutting mat? Would be useful to have the color selector also there on the calibrate page, except there it would apply to the raster not the pdf.
- The difference between minor and major lines is much better visible on the projected image than it looks on screen.
- But the important part - when projecting in cm, it still looks very crowded, even with minor/major. I think it's just the nature of working in cm where you'll always have 2.5 timer higher line density. The toolbar I was talking about won't help with that.

**Comment by roel-v** [comment]
Yeah that's what I do; I have a grid 40x80 drawn with pencil on masking tape underneath the transparent cutting mat, with additional lines every 10 cm horizontally and every 20 cm vertically. Those are just there because it seemed like a good idea, but tbh I haven't used them the few times I've calibrated now. Or do you mean I'd make a separate calibration sheet, that I remove from the work surface before cutting, and I can replace onto the fabric to double check?

**Comment by hluedeke** [comment]
No, I think you are doing what I was thinking you could do. I'm just trying to think through/justify this issue and potential solution. I have personally found that my "inner lines" don't always match up because my surface is not perfectly level. It's not enough to really affect most projects, in my opinion, so to me those additional lines are just "nice to haves" vs. being the actual calibration I am doing (which is on the outermost box).

**Comment by roel-v** [comment]
Also, I've done a quick informal inventory of metric cutting mats available online, and they all use the same major/minor gridding, except that they all have major lines every 5 centimeters unlike the 10cm that is in the Vercel link above. So if you decide the major/minor should stay, making the majors line up with what it looks like IRL is probably the way to go.

**Comment by courtneypattison** [comment]
> Also, I've done a quick informal inventory of metric cutting mats available online, and they all use the same major/minor gridding, except that they all have major lines every 5 centimeters unlike the 10cm that is in the Vercel link above. So if you decide the major/minor should stay, making the majors line up with what it looks like IRL is probably the way to go.

@roel-v You're a gem! Such a good idea to check that out!

I have a few ideas all of which include keeping the major grid lines, because I like those!
- Add ticks around the grid for the minor lines
- Make a dot grid for the minor lines
- Make a cross grid for the minor lines (+ at every minor line intersection)

**Comment by courtneypattison** [comment]
Okie doke, I've tried a dot grid as well and felt like it was less intuitive. I switched the colour back to white lines and agree that looks so much better. I'm thinking just add in the major lines. I tested it on the cm side of my mat and although it's a bit busy, but it matched my mat so I'm pretty happy with it. The [PR preview](https://pattern-projector-git-lines-courtney-pattisons-projects.vercel.app?_vercel_share=NcPMXWMwj5AsVdVhf6xlifGA7d6gUnX5](https://pattern-projector-git-lines-courtney-pattisons-projects.vercel.app/?_vercel_share=NcPMXWMwj5AsVdVhf6xlifGA7d6gUnX5)) has the style I'm thinking works. What do you folks think?

**Comment by hluedeke** [comment]
Haven't tried on a projector, but looks great from the browser.
