### ISSUE TITLE
Show/hide menu bar

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#64]
Remove some clutter from the menu bar by moving saved settings to another spot. Things like invert colours, maybe show grid, toggling dark/light mode, etc. Maybe a drawer to the right side that can be toggled open and closed like the layers menu.

**Comment by roel-v** [comment]
Personally I think having everything on the screen at once is a great convenience, and there aren't that many buttons yet that things get crowded or that you have to look hard for something, especially now with the (awesome) tool tips.

Especially things like show grid which you'll want to turn on/off a bunch of times while double checking at every step (measure twice, cut once!) you want to have at hand without having to open another menu or dialog I'd say.

The one thing is that most screens have more horizontal screen estate than they have vertical, especially compared to the h:w ratio of your typical cutting mat. From that perspective it makes more sense to have the toolbar on the side, although I personally like the cleaner look of having them at the top better.

**Comment by courtneypattison** [comment]
> Personally I think having everything on the screen at once is a great convenience, and there aren't that many buttons yet that things get crowded or that you have to look hard for something, especially now with the (awesome) tool tips.
> 

Agreed, lets wait until we run out of room. We can always have the side bar open by default so you can see everything but have the option to hide it.


> The one thing is that most screens have more horizontal screen estate than they have vertical, especially compared to the h:w ratio of your typical cutting mat. From that perspective it makes more sense to have the toolbar on the side, although I personally like the cleaner look of having them at the top better.

This is why I had the menu bar on the side originally. I keep waffling on this one! I think I like it better on the top as well. Maybe because it feels more standard? It would get kind of chunky on the side I like how the layers look there.

**Comment by hluedeke** [comment]
> From that perspective it makes more sense to have the toolbar on the side, although I personally like the cleaner look of having them at the top better.

I agree. I get that we are losing real estate, and that it will affect some people, but I also think the top toolbar makes the most intuitive sense. We could always implement a very intentional show/hide button that is much smaller (and doesn't have invisible layout divs) to remove the top toolbar for those who need it.

> Maybe because it feels more standard? It would get kind of chunky on the side I like how the layers look there.

Yes, I think that's exactly it. People know what to expect with a top toolbar, in my opinion. And yes, I also think allowing top toolbar + layers to be visible at the same time is wonderfully efficient.

**Comment by courtneypattison** [comment]
I just got a message from someone asking to be able to hide the menu bar! lol. I think a show/hide button makes sense. The way I had it before with the timeout/hover hiding is difficult to understand/use on a touch screen.

**Comment by courtneypattison** [comment]
Maybe [expand icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:expand_more:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=collapse)?

**Comment by hluedeke** [comment]
Sure 👍 I'd wrap it in some sort of outline to make it obvious that it's there.

This is going to sound like a weird recommendation - but I think we should at least experiment putting it in the center on the top. Centered might feel weird, but I think it's the least likely place someone will need to drag a corner.

Exit full screen mode should still also be visible. I'm thinking you will need to absolutely position these, as you won't want an invisible container div, as that would interfere with drag real estate.

**Comment by hluedeke** [comment]
The alternative to centered would be having that IconButton be smaller than normal, so that we use up the smallest amount of drag real estate as possible. When the toolbar is open, I picture the vertical center of that button on top of the lower border of the toolbar, or possibly the top border of that button (if it's more square) against the bottom border of the toolbar.

**Comment by courtneypattison** [comment]
I like both those ideas. We can also add more height to the menu bar if we give people the option to hide it. I think top centre feels consistent with other apps. Maybe a [minimize/maximize icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:minimize:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=line) top centre.

**Comment by hluedeke** [comment]
Sure 🤷‍♀️ I think either gets the point across
