### ISSUE TITLE
On touch devices, provide on-screen arrow buttons to move selected handle

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#68]
I don't know if it's possible to detect if the user has a keyboard or not; if not, maybe this should be a toggleable option. But when a corner handle is selected, show four arrow keys on the side of the display (maybe elsewhere? trade offs) that act as a limited onscreen keyboard. I find per-pixel movement much easier and faster than dragging but I can't get a keyboard to show up when doing this on my Android tablet. Having an on screen built-in alternative is I think the solution here.

**Comment by courtneypattison** [comment]
Agreed, the tablet experience is not as nice right now. Maybe a next button in the middle to go to the next corner. I'm loving tabbing through the corners and adjusting with the arrow keys.

Also, any ideas for showing tooltips on the touch screen? I'm not sure how other software does this. onClick with a timeout?

**Comment by hluedeke** [comment]
As far as I know, tooltip support isn't common in mobile - usually mobile has a different layout, which typically uses screen size  breakpoints to determine. I think we will need more than that here (will probably use user-agent) because smaller screen on a desktop will definitely not want visible buttons. I can take a stab at this one.

**Comment by j-huff** [comment]
Something that could be interesting would be a fine-adjust mode when dragging the selecting points on touch screen. Like tapping and holding the selecting circle without dragging for a few moments will activate it, and then your dragged movements will only move the selection circle at like a 5:1 ratio or something. Could help with calibration on touch screens.

**Comment by courtneypattison** [comment]
> Something that could be interesting would be a fine-adjust mode when dragging the calibration points on touch screen. Like tapping and holding the circle without dragging for a few moments will activate it, and then your dragged movements will only move the calibration point at like a 5:1 ratio or something. Could help with calibration on touch screens.

I really like this idea! The main issue I could see with it is if someone doesn't realize they've activated this mode and get super frustrated with movements being slowed down. Maybe a button or something to toggle it?
