### ISSUE TITLE
Adjust default width and height values

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#72]
Suggestions from Sasha Sewist summarized by me:
- make 16x24" the default for the calibration grid size to help with people being confused about it not fitting their mats
- Have light gray grid lines that come out from the calibration grid to help with people being confused about being able to cut outside grid
- Maybe hide height and width input to stop people from choosing custom ones and being confused 

My thoughts:
I like the idea of changing the default to 16x24! I think the least common denominator approach makes sense here. Have you tested to see if that size has sufficient precision for cutting on larger mats?

I'm wary of hiding the height and width input. I think that might make people think they have to use that size. But I could be convinced otherwise!

I also like the idea of extending the grid in a different colour so people understand that they can cut anywhere!

PP really needs help with making it more obvious how it works. I'm kind of thinking that the first time someone opens the calibrate page, there is a pop up with a gif showing how to drag the calibration grid with some text like "Drag the corners of the grid to at least 16x24 in width and height. Input the width and height of your grid in the top menu. Don't worry, you can cut outside of the area of the grid once it's calibrated!" Then we could have an icon button on the bottom that would open that pop up again if someone wants to check it out again but it won't pop up automatically after the first visit. Thoughts?

Sasha agreed to join the PP Github organization so we might be getting her expert feedback on here, woot woot!

**Comment by hluedeke** [comment]
I am fine changing the default size 🤷‍♀️ whatever works! I’m also hesitant to remove the size of the grid. I think a lot of people change those numbers to match their grid size (if they are able) as that is the easiest way to calibrate.

As far as making it more obvious how it works…I mean, we could try to get fancy with tooltips and all that, but a lot of people will just want video tutorials, documentation with screenshots, etc.

I think if we put out a well-scripted video (or found a group member who wanted do it) that explains a couple of common scenarios, I think that might eliminate a lot of confusion.

 Like: 1) changing the grid size to match your mat, 2) steps for if your mat is too big for the grid, 3) steps for (whatever else). The presenter would then open a (public domain) pdf on the grid and explain how pdfs work (bigger than the grid, etc)


There might be some things we can do from the technical side, like what you’re saying, but I’m always a little slow to implement things like that. Unless they are executed flawlessly, they can potentially add to the confusion.

I’d try finding help down the video route first (if it were just me). A lot of sewists are used to watching videos, reading patterns, and following step by step instructions.

**Comment by hluedeke** [comment]
> Have light gray grid lines that come out from the calibration grid to help with people being confused about being able to cut outside grid

Would this be solved with roel-v’s suggested workflow of auto-hiding the calibration grid when you open a pdf?

**Comment by hluedeke** [comment]
Yes, I think we should try that first and see how it goes! You can definitely over-optimize for intuitiveness (ask me how I know  🤪), and I think what we already have is pretty good. So let's try this first and see what happens. If people are still stuck, we can start looking at more technically intrusive options 😁
