### ISSUE TITLE
Add updates to the landing page so people know when new features/fixes have been added

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#76]
This has been requested by a few people. Maybe a update highlights section with the newest features/fixes and click to expand for previous updates? This might be the time to add that versioning suggested by @hluedeke to the site in some way and/or we can tag releases in GitHub.

**Comment by hluedeke** [comment]
We can start with a CHANGELOG.md file, which I understand is not very visible to the end user. But it's a start to recording changes made in the application (and can be drawn from to create the user-facing page).

**Comment by courtneypattison** [comment]
I think that’s a great idea! Maybe add a line with each PR and I can add the date when I merge into main or something like that?

**Comment by hluedeke** [comment]
I think we can add our own lines to "Unreleased" and then you can move them into a release/date when you merge, yes. I have a sample file created, so you can take a look here in a bit when I get it PR'd

**Comment by courtneypattison** [comment]
Added in #175
