### ISSUE TITLE
Move to Weblate (or other tool) for translations

### ISSUE THREAD

**Issue by roel-v** [Pattern-Projector/pattern-projector#77]
Courtney you mentioned as an aside in a now-closed issue you were looking at Weblate, is that still ongoing? You want me to do anything on that?

**Comment by courtneypattison** [comment]
I just got an email from Weblate a couple of days ago saying I need to finish my registration and I ignored it to work on the stitching lol. I'm sorry for slacking on this one. I'll try to finish getting it setup today. I think there's an authentication issue.

**Comment by courtneypattison** [comment]
I think I fixed the authentication issue. Now I'm just waiting for approval for libre hosting. If PP gets approved, we can start testing it out more thoroughly!

**Comment by roel-v** [comment]
Haha no need to apologize, you're on a roll as it is, can't do everything at once. Whenever you're ready.
