### ISSUE TITLE
Icon source? + Discussions

### ISSUE THREAD

**Issue by j-huff** [Pattern-Projector/pattern-projector#81]
Hi, I was working on some features for my fork today and I needed to add some icons. I couldn't find anywhere that mentions where the current icons are sourced from and I was hoping to keep with the same theme. Where should I source new icons from?

Also, I understand that this shouldn't be submitted as an issue, but the Discussions page isn't enabled for this issue. Should you consider enabling it? Or is there some other method that a question like this should be asked?

**Comment by courtneypattison** [comment]
> Hi, I was working on some features for my fork today and I needed to add some icons. I couldn't find anywhere that mentions where the current icons are sourced from and I was hoping to keep with the same theme. Where should I source new icons from?

Sorry, this should be documented somewhere! They're [material icons](https://fonts.google.com/icons).
> 
> Also, I understand that this shouldn't be submitted as an issue, but the Discussions page isn't enabled for this issue. Should you consider enabling it? Or is there some other method that a question like this should be asked?

Great idea, done!
