### ISSUE TITLE
Show zoom percentage when someone zooms

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#86]
Someone may zoom accidentally so we should show the zoom level in this case. Reported by someone using PP on a tablet. I wish we could just turn off zooming but i don’t think that’s possible!

**Comment by hluedeke** [comment]
https://stackoverflow.com/questions/22999829/disable-chrome-pinch-zoom-for-use-in-kiosk

**Comment by courtneypattison** [comment]
Lol well touch action none seems like a super simple approach! I think I read somewhere that zoom changes the device pixel ratio which we access in the custom renderer so I was thinking of saving the ratio on load and setting it based on that rather than the current device pixel ratio. Making zooming of the pdf viewer not possible. If setting the touch action works, that would so much better!

**Comment by hluedeke** [comment]
I have no idea if it works, just thought I'd throw it in there just in case!
