### ISSUE TITLE
Grid orientation issue

### ISSUE THREAD

**Issue by hluedeke** [Pattern-Projector/pattern-projector#92]
I don’t have a fix for this one off the top of my head, but a user in PFS flipped their calibration height/width measurements (aka entered them backwards). This caused confusion as their projected file was very distorted.

I think the confusion was due to the same issue(s) we have seen when people have a rotated projector image from what they see on their screen.

**Comment by hluedeke** [comment]
This feels like something that perhaps belongs in a troubleshooting FAQ. Or maybe a step in the documentation for calibration should be “ensure the calibration grid lines are exactly 1in/1cm before proceeding to project”

**Comment by hluedeke** [comment]
Another idea would be to add the measurement to each dimension of the calibration grid, like an axis label. This would only be in calibration mode.

**Comment by courtneypattison** [comment]
I like that idea! Or we could number the lines line on a cutting mat.

**Comment by hluedeke** [comment]
I like that idea too, the only thing I would be concerned about is readability, since we know text gets hard to read at certain sizes. But I think it might be easier to understand in general!
