### ISSUE TITLE
Skew issue when scrolling

### ISSUE THREAD

**Issue by hluedeke** [Pattern-Projector/pattern-projector#94]
I was just noticing while testing the stitch menu that if someone uses the scrollbars on the browser window, then the skew continues to grow/change/diverge and will probably distort relative to the initial calibration. I think this wasn't an issue before removing the calibration grid by default because it was intuitive to drag the pdf over the box to "fit". Now, without the box/outline visible, people may try to scroll their browser window, creating this distortion.

This could be related to an issue a user was having where their grid lines were shown as not square to the calibration.

Possible solutions:
Disable scolling on body/container component - don't allow people to scroll beyond the visible window.
Reintroduce the calibration grid, but perhaps just the outline. This makes it less busy but still shows where the browser scroll should be.

**Comment by courtneypattison** [comment]
Oooo, I did not think about this one. Unintended consequences! I tried stopping scrolling in the stitch menu PR and like it. What do you think?

**Comment by hluedeke** [comment]
I’ll check it out when I have a chance!

**Comment by hluedeke** [comment]
Verified!
