### ISSUE TITLE
Add fix to horizontal or vertical on drag

### ISSUE THREAD

**Issue by courtneypattison** [Pattern-Projector/pattern-projector#96]
I’m not sure how we’d want to implement this one but some people use scroll bars move in a straight line to do things like lengthen a skirt. I think it would be really nice to keep one direction fixed in some way when dragging. On the computer it would be easy to do this by holding alt or something like that but trickier for tablet.

**Comment by hluedeke** [comment]
Do you ever really have one directional scroll on a tablet anyway?

**Comment by courtneypattison** [comment]
Ooo that’s true!

**Comment by j-huff** [comment]
When you say drag, you mean dragging the pattern? So in project mode, if you hold alt/control when dragging the pattern with the mouse, the pattern will only move exactly horizontal/vertical relative to the projection plane?

If I'm understanding this correctly, I might take a crack at it. Might even be nice to display some text showing how far the pattern has been dragged to help If someone is trying to move it exactly X inches.

**Comment by j-huff** [comment]
When implementing this change, it became much more apparent that moving the cursor off of the dragged element causes the dragged elements position to stop being updated (much easier to move the cursor off the element when you are constraining the elements movement to a single axis). Unless this is intended behavior, we should probably open a separate issue for that.
